amcl:
  ros__parameters:
    use_sim_time: True
    robot_model_type: "differential"
    min_particles: 500
    max_particles: 2000
    laser_model_type: "likelihood_field"
    pf_err: 0.05
    pf_z: 0.99

controller_server:
  ros__parameters:
    use_sim_time: True
    controller_frequency: 20.0
    progress_checker:
      plugin: "nav2_controller::SimpleProgressChecker"
    goal_checker:
      plugin: "nav2_controller::SimpleGoalChecker"
    controller_plugins: ["FollowPath"]
    FollowPath:
      plugin: "dwb_core::DWBLocalPlanner"
      debug_trajectory_details: True

planner_server:
  ros__parameters:
    use_sim_time: True
    planner_frequency: 10.0
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_navfn_planner/NavfnPlanner"
